# Generated by Django 3.1.6 on 2021-02-12 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210212_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='texte',
            old_name='para',
            new_name='msg',
        ),
        migrations.RemoveField(
            model_name='texte',
            name='sous_titre',
        ),
        migrations.RemoveField(
            model_name='texte',
            name='titre',
        ),
    ]
