# Generated by Django 3.1.6 on 2021-02-11 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieTexte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=100, null=True)),
                ('partie', models.CharField(max_length=100, null=True)),
                ('designation', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='texte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=500, null=True)),
                ('sous_titre', models.CharField(max_length=1000, null=True)),
                ('para', models.TextField(null=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='texte.categorietexte')),
            ],
        ),
    ]
